# Generated by Django 5.0.6 on 2024-10-21 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_subcategory_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_id',
            new_name='id',
        ),
    ]
