# Generated by Django 5.0.6 on 2024-11-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_product_id_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('mess_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('Phone', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
